branches:
  only:
    - master

language: python

python:
  - "3.6"

git:
  depth: false

install:
  - pip install -r requirements.txt

script:
  - if [ $TRAVIS_EVENT_TYPE == "cron" ];
    then python scripts/fetch_projects.py;
    else python scripts/fetch_projects.py;
    fi;

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $OAUTH_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
